run 'mypy' via pre-commit, enforce 'pre-commit' checks in CI (#92)
Fixes #39 
Fixes #36

Changes:

* adds a CI job that runs `pre-commit`
* improvements to `pr.yaml`:
  - only running tests on PRs (not merges to `main`)
- automatically cancelling in-progress runs when a new commit is pushed
- updates workflow name to just `pr` (to make the checks summary on PRs
a little easier to read, and for consistency with other RAPIDS repos)
* removes unused configuration from `pyproject.toml` (looks like some of
this may have just been copied over from other projects)
* fixes `mypy` warnings:
* adds `mypy` hook to `pre-commit` configuration

```text
rapids_cli/doctor/doctor.py:23: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]
rapids_cli/doctor/doctor.py:24: error: Incompatible types in assignment (expression has type "None", variable has type "Exception")  [assignment]
rapids_cli/doctor/doctor.py:25: error: Incompatible types in assignment (expression has type "None", variable has type "list[Warning]")  [assignment]
rapids_cli/doctor/doctor.py:97: error: Argument "value" to "CheckResult" has incompatible type "None"; expected "str"  [arg-type]
rapids_cli/doctor/doctor.py:98: error: Argument "error" to "CheckResult" has incompatible type "Exception | None"; expected "Exception"  [arg-type]
rapids_cli/doctor/doctor.py:99: error: Argument "warnings" to "CheckResult" has incompatible type "list[WarningMessage] | None"; expected "list[Warning]"  [arg-type]
rapids_cli/doctor/doctor.py:107: error: "Warning" has no attribute "message"  [attr-defined]
```